require 'robot_arm'
robot_arm:load_level('exercise 11')
robot_arm.speed = 0.7
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
 elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
  elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left() 
   end
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:drop()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end 
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end 
robot_arm:drop()
if color == not "red" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
end 
robot_arm:move_right()
robot_arm:grab()
color = robot_arm:scan()
if color == "red" then
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
robot_arm:move_right()
  robot_arm:drop()
elseif color == "blue" then
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "green" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
elseif color == "white" then 
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
robot_arm:move_left()
end
robot_arm:drop()


